### ISSUE TITLE
Bot no longer starts - discord permission change

### ISSUE THREAD

**Issue by brichardson1991** [Noah-Huppert/discord-azure-boot#3]
Sorry to be the bearer of bad news but this no longerworks. @Noah-Huppert 

```
/opt/discord-azure-bot/node_modules/discord.js/src/rest/RequestHandler.js:243
      throw new DiscordAPIError(request.path, data, request.method, res.status);
            ^
DiscordAPIError: Bots cannot use this endpoint
    at RequestHandler.execute (/opt/discord-azure-bot/node_modules/discord.js/src/rest/RequestHandler.js:243:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async RequestHandler.push (/opt/discord-azure-bot/node_modules/discord.js/src/rest/RequestHandler.js:49:14)
    at async GuildApplicationCommandManager.setPermissions (/opt/discord-azure-bot/node_modules/discord.js/src/managers/ApplicationCommandManager.js:245:20)
```

The bot no longer starts due to an update to discord

**Comment by catvec** [comment]
Shoot! One of my other bots just got taken out by that change. I'll try and release a fix asap.

**Comment by catvec** [comment]
Aha @brichardson1991 I found the issue! I was using the old method of registering slash commands instead of the new `SlashCommandBuilder` and Discord REST client. I hope to have a fix released by the end of this weekend.

**Comment by brichardson1991** [comment]
Ah perfect, I look forward to it working again and seeing the change you make so hopefully I can help in the future.

**Comment by catvec** [comment]
Alright @brichardson1991 it should be all good to go 😃 . You shouldn't need to make any changes to your config file or anything. Just make sure you are running the latest source code from the `v0.0.2` tag.

> hopefully I can help in the future.

Absolutely no pressure to contribute but if you do want to I would be glad to accept PR's.
